### ISSUE TITLE
website doesn't load

### ISSUE THREAD

**Issue by thewanderingtraderm** [uup-dump/website#227]
whenever i visit the website it comes up with a 502 bad gateway error

**Comment by saigauthamr** [comment]
I have the same issue. Need an iso urgently.

**Comment by RealEnthousiast** [comment]
UUP dump needs attention of the owner, he will check it out asap, in the mean time:

https://massgrave.dev/msdl/

**Comment by RealEnthousiast** [comment]
UUP dump is fixed

**Comment by mrusli70** [comment]
still the same, i could not even go to the uupdump.net website it says badgateway. please fix the server problems.

**Comment by unwillinglyawesome** [comment]
![image](https://github.com/uup-dump/website/assets/129231322/ee7571e7-0574-4a21-86f0-38e55a201f38)
![image](https://github.com/uup-dump/website/assets/129231322/c81db1df-42a3-48e5-b1c8-1e4ec1db03ee)

Up and down, up and down 😞

**Comment by crrashh1542** [comment]
It got unavailable again some days ago, i could not open the website with the error `ERR_CONNECTION_CLOSED`.

**Comment by RockyTheProtogen** [comment]
Yea, all i got is this:
```fetch
fetch("https://uupdump.net/", {
  "headers": {
    "sec-ch-ua": "\"Not/A)Brand\";v=\"99\", \"Microsoft Edge\";v=\"115\", \"Chromium\";v=\"115\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "upgrade-insecure-requests": "1"
  },
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "omit"
});
```

 `ERR_CONNECTION_TIMED_OUT` is the only error I get.

**Comment by nutterthanos** [comment]
Site dead use local server:
https://canary.discord.com/channels/600104690684002321/600104690684002323/1053404611110776873
Discord join link: https://discord.com/invite/yVRbtb2

**Comment by dangerous2022** [comment]
ERR_CONNECTION_TIMED_OUT

**Comment by Breizyann** [comment]
This site can’t be reacheduupdump.net took too long to respond.

Try:
Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
[Running Windows Network Diagnostics](javascript:diagnoseErrors())

ERR_CONNECTION_TIMED_OUT

C:\Windows\System32>ping uupdump.net
→ not responding to the ping too. 

Thank for helping.

Kind regards,
Yann

**Comment by ItsukaHiro** [comment]
This is update from offical Discord:
`The uupdump.net domain is not up anymore, any other domain is NOT an official clone, best to use the UUP dump APP instead`
